import os

os.chdir("C:\\Users\\rusiecki\\Downloads\\musicdir")

for filename in os.listdir('C:\\Users\\rusiecki\\Downloads\\musicdir'):
    print(filename)
    newname = filename.replace("(", " ")
    newname = newname.replace(")", "")
    newname = newname.replace("[", " ")
    newname = newname.replace("]", "")
    newname = newname.replace("&", " ")
    newname = newname.replace("_", " ")
    newname = newname.replace("!", "")
    newname = newname.replace("?", "")
    newname = newname.replace("*", "")
    newname = newname.replace("\"", "")
    newname = newname.replace("'", "")
    newname = newname.replace("$", "")
    newname = newname.replace("+", "")
    newname = newname.replace("@", "")

    newname = newname.replace("ą", "a")
    newname = newname.replace("ć", "c")
    newname = newname.replace("ś", "s")
    newname = newname.replace("ń", "n")
    newname = newname.replace("ó", "o")
    newname = newname.replace("ż", "z")
    newname = newname.replace("ź", "z")
    newname = newname.replace("ł", "l")
    newname = newname.replace("Ą", "A")
    newname = newname.replace("Ć", "C")
    newname = newname.replace("Ś", "S")
    newname = newname.replace("Ń", "N")
    newname = newname.replace("Ó", "O")
    newname = newname.replace("Ż", "Z")
    newname = newname.replace("Ź", "Z")
    newname = newname.replace("Ł", "L")
    os.rename(filename, newname)

# os.system('pause')
